# Generated by Django 5.0.3 on 2024-04-01 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userordermodel',
            old_name='cvv',
            new_name='CVV',
        ),
    ]
